// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gCodeJournal.Model;

#nullable disable

namespace gCodeJournal.Model.Migrations
{
    [DbContext(typeof(GCodeJournalDbContext))]
    partial class GCodeJournalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("gCodeJournal.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("gCodeJournal.Model.Filament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPerWeight")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilamentColourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilamentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrintingProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReorderLink")
                        .HasMaxLength(2083)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilamentColourId");

                    b.HasIndex("FilamentTypeId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PrintingProjectId");

                    b.ToTable("Filaments");
                });

            modelBuilder.Entity("gCodeJournal.Model.FilamentColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilamentColours");
                });

            modelBuilder.Entity("gCodeJournal.Model.FilamentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilamentTypes");
                });

            modelBuilder.Entity("gCodeJournal.Model.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("gCodeJournal.Model.ModelDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Length")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelDesigns");
                });

            modelBuilder.Entity("gCodeJournal.Model.PrintingProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilamentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelDesignId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ModelDesignId");

                    b.ToTable("PrintingProjects");
                });

            modelBuilder.Entity("gCodeJournal.Model.Filament", b =>
                {
                    b.HasOne("gCodeJournal.Model.FilamentColour", "Colour")
                        .WithMany("Filaments")
                        .HasForeignKey("FilamentColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gCodeJournal.Model.FilamentType", "Type")
                        .WithMany("Filaments")
                        .HasForeignKey("FilamentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gCodeJournal.Model.Manufacturer", "Manufacturer")
                        .WithMany("Filaments")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gCodeJournal.Model.PrintingProject", null)
                        .WithMany("Filaments")
                        .HasForeignKey("PrintingProjectId");

                    b.Navigation("Colour");

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("gCodeJournal.Model.PrintingProject", b =>
                {
                    b.HasOne("gCodeJournal.Model.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gCodeJournal.Model.ModelDesign", "Model")
                        .WithMany()
                        .HasForeignKey("ModelDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("gCodeJournal.Model.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("gCodeJournal.Model.FilamentColour", b =>
                {
                    b.Navigation("Filaments");
                });

            modelBuilder.Entity("gCodeJournal.Model.FilamentType", b =>
                {
                    b.Navigation("Filaments");
                });

            modelBuilder.Entity("gCodeJournal.Model.Manufacturer", b =>
                {
                    b.Navigation("Filaments");
                });

            modelBuilder.Entity("gCodeJournal.Model.PrintingProject", b =>
                {
                    b.Navigation("Filaments");
                });
#pragma warning restore 612, 618
        }
    }
}
